nrinaudo/kantan.sbt

core/src/main/scala/kantan/sbt/KantanPlugin.scala

[#29] Fix unused-imports for 2.11

---

core/src/main/scala/kantan/sbt/KantanPlugin.scala
kantan/src/main/scala/kantan/sbt/kantan/KantanKantanPlugin.scala

[#31] Update to Scala 2.11.12

---

core/src/main/scala/kantan/sbt/UnpublishedPlugin.scala

[#33] Fix sbt-release for unpublished modules

---

core/src/main/scala/kantan/sbt/DocumentationPlugin.scala

[#37] Fix ghpagesPushSite not running makeSite

---

core/src/main/scala/kantan/sbt/KantanPlugin.scala

[#40] Fix unused warnings in tut

---

project/BuildPlugin.scala

Fixes #43.
Note that this depends on #44 and should not be merged before.

[#43] Skip scripted when skip-tests is enabled

---

.travis.yml

[#48] Add openjdk8 and oraclejdk9 to Travis

---

core/src/main/scala/kantan/sbt/KantanScalafmtPlugin.scala
core/src/main/scala/kantan/sbt/Resources.scala
kantan/src/sbt-test/kantan/scalafmtConfig/build.sbt
kantan/src/sbt-test/kantan/scalafmtConfig/project/plugins.sbt
kantan/src/sbt-test/kantan/scalafmtConfig/test

[#50] Make copyScalafmtConfig honour scalafmtConfig

---

kantan/src/sbt-test/kantan/scalastyleConfig/build.sbt
kantan/src/sbt-test/kantan/scalastyleConfig/project/plugins.sbt
kantan/src/sbt-test/kantan/scalastyleConfig/test
scalastyle/src/main/scala/kantan/sbt/scalastyle/KantanScalastylePlugin.scala

[#55] Add support for scalastyleConfig

---

core/src/sbt-test/boilerplate/header/test
core/src/sbt-test/core/header/test
core/src/sbt-test/core/warnings/test
core/src/sbt-test/published/pom/test
core/src/sbt-test/strict/warts/test

Turns out this was already done for most tests...
Fixes #53

[#53] Comment tests

---

kantan/src/main/scala/kantan/sbt/kantan/KantanKantanPlugin.scala
project/BuildPlugin.scala
project/DocumentationPlugin.scala

[#59]: Fix release process

---

README.md
docs/src/site-preprocess/index.md

[#61] Fix documentation post-2.0.0

---

core/src/sbt-test/core/laws/build.sbt
core/src/sbt-test/core/laws/core/src/main/scala/Foo.scala
core/src/sbt-test/core/laws/core/src/test/scala/FooTest.scala
core/src/sbt-test/core/laws/laws/src/main/scala/Bar.scala
core/src/sbt-test/core/laws/project/build.properties
core/src/sbt-test/core/laws/project/plugins.sbt
core/src/sbt-test/core/laws/test

[#66] Add tests for the laws function

---

kantan/src/main/resources/kantan/sbt/scalastyle-config.xml

[#62] Remove unnecessary scalastyle checks

---

build.sbt
docs/src/site-preprocess/defaults.md
project/Versions.scala

[#70] Add coursier as a dependency

---

docs/src/site-preprocess/scalajs.md
scalajs/src/main/scala/kantan/sbt/scalajs/KantanScalaJsPugin.scala

[#73] Add validateJS and validateJVM

---

.travis.yml

[#72] Update travis cache instructions to include coursier's cache

---

.travis.yml
core/src/main/scala/kantan/sbt/KantanPlugin.scala
kantan/src/main/scala/kantan/sbt/kantan/KantanKantanPlugin.scala
project/BuildPlugin.scala
project/Versions.scala
project/build.properties
project/plugins.sbt

[#78] Update to Scala 2.12.6

---

project/Versions.scala
project/build.properties

[#80] Remove Versions.scalafmt

---

kantan/src/main/resources/kantan/sbt/scalafmt.conf
kantan/src/main/resources/kantan/sbt/scalastyle-config.xml
scalafmt/src/main/scala/kantan/sbt/scalafmt/KantanScalafmtPlugin.scala

[#105] Update style checking rules

---

kantan/src/main/resources/kantan/sbt/scalafmt.conf

[#116] Disable flaky scalafmt rule

---

core/src/main/scala/kantan/sbt/KantanPlugin.scala

[#123] Drop support for Scala 2.11 from scalac options

---

README.md

- Fix build status badge
- Fix version badge
- Replace by two badges (sbt 1.0, sbt 0.13)

chore: Fix CI and latest version badges
